select * from customer
limit 5;
--Q1. What is the total revenue generated by male vs female customers.
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

--Q2. which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' AND purchase_amount >=(select AVG(purchase_amount) from customer)

--Q3. which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) AS "Average Review Rating"
from customer
group by item_purchased
Order by AVG(review_rating) DESC
limit 5;

--Q4. Compare the average purchase amount between standard and express shipping.
select ROUND(AVG(purchase_amount),2) AS average_purchase_amount, shipping_type
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customer spend more?Compare average spend and total revenue 
-- between subscribers and non subscribers

select subscription_status,
count(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend DESC;


--Q6. which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' Then 1 else 0 END) / COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customer into new,returnning and loyal based on their total
--number of previous purchases, and show the count of each segment.
WITH customer_type AS (
select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returnning'
	ELSE 'Loyal'
	END AS customer_segment
from customer 
)

select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. what are the top 3 most purchased products  within each category?
WITH item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank < 4;

--Q9. Are customers who are  repeat buyers(more than 5 previous) also likely to be subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;
